window.ATC_EXAMPLES_CONFIG = {
  folders: [
    "examples/01",
    "examples/02",
    "examples/03",
    "examples/04",
    "examples/05",
    "examples/06",
    "examples/07",
    "examples/08",
    "examples/09",
    "examples/10",
    "examples/11",
    "examples/12",
  ],
  selectionNote:
    "Each of these 12 samples contains an author-selected recording and its matched base or adapted comparison. Pairs share the same message, reference audio, and generation seed. These are curated examples, not representative outputs. Automatic scores and informal listening preferences do not establish perceptual identity, listener or pilot acceptance, or operational spoofing success.",
  controllerRecordings: {
    gf1: [
      {
        sourceId: "gf1_01_018",
        controller: "gf1",
        text: "Alitalia three six four reims one three three decimal eight two good bye.",
        durationSeconds: 3.5870625,
        src: "examples/controllers/gf1/gf1_01_018.wav",
      },
      {
        sourceId: "gf1_01_199",
        controller: "gf1",
        text: "Alitalia three seven zero identified aosta st prex dijon flight level three two zero.",
        durationSeconds: 5.38225,
        src: "examples/controllers/gf1/gf1_01_199.wav",
      },
      {
        sourceId: "gf1_01_216",
        controller: "gf1",
        text: "Lufthansa four six five two climb to flight level three five zero.",
        durationSeconds: 3.1986875,
        src: "examples/controllers/gf1/gf1_01_216.wav",
      },
      {
        sourceId: "gf1_01_057",
        controller: "gf1",
        text: "Alitalia three zero one milano one two five eight five good bye.",
        durationSeconds: 3.1034375,
        src: "examples/controllers/gf1/gf1_01_057.wav",
      },
      {
        sourceId: "gf1_01_197",
        controller: "gf1",
        text: "Transwede one zero seven set course direct to bilsa.",
        durationSeconds: 2.886,
        src: "examples/controllers/gf1/gf1_01_197.wav",
      },
      {
        sourceId: "gf1_01_147",
        controller: "gf1",
        text: "Bonjour speedbird eight three papa xray squawk ah five seven four six.",
        durationSeconds: 3.8781875,
        src: "examples/controllers/gf1/gf1_01_147.wav",
      },
      {
        sourceId: "gf1_01_028",
        controller: "gf1",
        text: "Bonjour viva nine zero eight one identified cleared ah kines st prex willisau flight level three four zero.",
        durationSeconds: 6.007125,
        src: "examples/controllers/gf1/gf1_01_028.wav",
      },
      {
        sourceId: "gf1_01_231",
        controller: "gf1",
        text: "Iberia three four seven three climb to flight level three five zero.",
        durationSeconds: 3.3383125,
        src: "examples/controllers/gf1/gf1_01_231.wav",
      },
      {
        sourceId: "gf1_01_059",
        controller: "gf1",
        text: "Belgian airforce ah three three four bonjour identified cleared ah passeiry epinal flight level three two zero.",
        durationSeconds: 9.3416875,
        src: "examples/controllers/gf1/gf1_01_059.wav",
      },
      {
        sourceId: "gf1_01_218",
        controller: "gf1",
        text: "Lufthansa four six five two geneva one two eight one five good bye.",
        durationSeconds: 3.8688125,
        src: "examples/controllers/gf1/gf1_01_218.wav",
      },
      {
        sourceId: "gf1_01_047",
        controller: "gf1",
        text: "Sabena nine seven zero are you on course to arbos.",
        durationSeconds: 2.8870625,
        src: "examples/controllers/gf1/gf1_01_047.wav",
      },
      {
        sourceId: "gf1_01_060",
        controller: "gf1",
        text: "Europa three eight one ah bonjour identified cleared kines st prex willisau flight level three four zero.",
        durationSeconds: 7.535125,
        src: "examples/controllers/gf1/gf1_01_060.wav",
      },
      {
        sourceId: "gf1_01_225",
        controller: "gf1",
        text: "Sunwing five two zero three report position.",
        durationSeconds: 2.788,
        src: "examples/controllers/gf1/gf1_01_225.wav",
      },
      {
        sourceId: "gf1_01_029",
        controller: "gf1",
        text: "Sabena nine seven zero bonjour identified stop climb flight level three two zero.",
        durationSeconds: 4.5135625,
        src: "examples/controllers/gf1/gf1_01_029.wav",
      },
      {
        sourceId: "gf1_01_063",
        controller: "gf1",
        text: "And topswiss four five seven eight own navigation tour du pin.",
        durationSeconds: 2.99975,
        src: "examples/controllers/gf1/gf1_01_063.wav",
      },
      {
        sourceId: "gf1_01_055",
        controller: "gf1",
        text: "Lufthansa four seven three one zurich one three four six good bye.",
        durationSeconds: 3.380625,
        src: "examples/controllers/gf1/gf1_01_055.wav",
      },
      {
        sourceId: "gf1_01_178",
        controller: "gf1",
        text: "L t u seven seven five six ah geneva one two eight one five good bye.",
        durationSeconds: 3.9306875,
        src: "examples/controllers/gf1/gf1_01_178.wav",
      },
      {
        sourceId: "gf1_01_154",
        controller: "gf1",
        text: "Two six nine zero contact ah marseille one two five eight five good bye.",
        durationSeconds: 4.2433125,
        src: "examples/controllers/gf1/gf1_01_154.wav",
      },
      {
        sourceId: "gf1_01_158",
        controller: "gf1",
        text: "And report your position.",
        durationSeconds: 1.3200625,
        src: "examples/controllers/gf1/gf1_01_158.wav",
      },
      {
        sourceId: "gf1_01_153",
        controller: "gf1",
        text: "Cross air two six nine zero climb to flight level three one zero own navigation tour du pin.",
        durationSeconds: 4.8599375,
        src: "examples/controllers/gf1/gf1_01_153.wav",
      },
      {
        sourceId: "gf1_01_038",
        controller: "gf1",
        text: "Cross air five one two descend to flight level two eight zero.",
        durationSeconds: 3.0809375,
        src: "examples/controllers/gf1/gf1_01_038.wav",
      },
      {
        sourceId: "gf1_01_062",
        controller: "gf1",
        text: "Topswiss four five seven eight contact marseille one two five decimal eight five good bye.",
        durationSeconds: 6.00325,
        src: "examples/controllers/gf1/gf1_01_062.wav",
      },
      {
        sourceId: "gf1_01_049",
        controller: "gf1",
        text: "Roger continue present heading.",
        durationSeconds: 1.888125,
        src: "examples/controllers/gf1/gf1_01_049.wav",
      },
      {
        sourceId: "gf1_01_072",
        controller: "gf1",
        text: "Ascot nine three one nine identified cleared ah st prex rolampont flight level three two zero.",
        durationSeconds: 6.7399375,
        src: "examples/controllers/gf1/gf1_01_072.wav",
      },
      {
        sourceId: "gf1_01_132",
        controller: "gf1",
        text: "Aero lloyd five six zero marseille one two five eight five good bye.",
        durationSeconds: 3.7571875,
        src: "examples/controllers/gf1/gf1_01_132.wav",
      },
      {
        sourceId: "gf1_01_090",
        controller: "gf1",
        text: "Bonjour hapag lloyd ah one seven one identified passeiry bilsa flight level two nine zero.",
        durationSeconds: 5.077625,
        src: "examples/controllers/gf1/gf1_01_090.wav",
      },
      {
        sourceId: "gf1_01_064",
        controller: "gf1",
        text: "Viva nine zero eight one turn left heading three five zero.",
        durationSeconds: 3.670125,
        src: "examples/controllers/gf1/gf1_01_064.wav",
      },
      {
        sourceId: "gf1_01_138",
        controller: "gf1",
        text: "Bonjour l t u seven seven five six call you back break air portugal four one one three climb to flight level three six zero.",
        durationSeconds: 6.6238125,
        src: "examples/controllers/gf1/gf1_01_138.wav",
      },
      {
        sourceId: "gf1_01_091",
        controller: "gf1",
        text: "Swissair six seven five two turn left to kines.",
        durationSeconds: 3.4191875,
        src: "examples/controllers/gf1/gf1_01_091.wav",
      },
      {
        sourceId: "gf1_01_141",
        controller: "gf1",
        text: "Ukay six two five milano on one two five eight five good bye.",
        durationSeconds: 3.399125,
        src: "examples/controllers/gf1/gf1_01_141.wav",
      },
    ],
    gm1: [
      {
        sourceId: "gm1_02_110",
        controller: "gm1",
        text: "Bonjour french line three five six one cleared direct torino flight level three one zero.",
        durationSeconds: 6.5670625,
        src: "examples/controllers/gm1/gm1_02_110.wav",
      },
      {
        sourceId: "gm1_02_106",
        controller: "gm1",
        text: "Viva nine zero eight one contact ah zurich one three four decimal six good bye.",
        durationSeconds: 5.8705,
        src: "examples/controllers/gm1/gm1_02_106.wav",
      },
      {
        sourceId: "gm1_02_069",
        controller: "gm1",
        text: "Roystar six two six four nine four bonjour cleared kines st prex arbos epinal flight level.",
        durationSeconds: 8.0914375,
        src: "examples/controllers/gm1/gm1_02_069.wav",
      },
      {
        sourceId: "gm1_02_049",
        controller: "gm1",
        text: "Saudia one five five descend to flight level three one zero due to traffic and own navigation direct to dijon.",
        durationSeconds: 7.6074375,
        src: "examples/controllers/gm1/gm1_02_049.wav",
      },
      {
        sourceId: "gm1_02_144",
        controller: "gm1",
        text: "Six five three contact marseille one two five eight five good bye.",
        durationSeconds: 3.589625,
        src: "examples/controllers/gm1/gm1_02_144.wav",
      },
      {
        sourceId: "gm1_02_134",
        controller: "gm1",
        text: "Hapag lloyd six five three own navigation direct to bilsa.",
        durationSeconds: 3.4943125,
        src: "examples/controllers/gm1/gm1_02_134.wav",
      },
      {
        sourceId: "gm1_02_052",
        controller: "gm1",
        text: "Foxtrot foxtrot lima bonjour cleared direct torino flight level three one zero.",
        durationSeconds: 4.354875,
        src: "examples/controllers/gm1/gm1_02_052.wav",
      },
      {
        sourceId: "gm1_02_003",
        controller: "gm1",
        text: "Alitalia three hundred bonjour squawk five seven six three.",
        durationSeconds: 3.870375,
        src: "examples/controllers/gm1/gm1_02_003.wav",
      },
      {
        sourceId: "gm1_02_173",
        controller: "gm1",
        text: "November one four five whiskey contact radar on one two eight decimal one five good bye.",
        durationSeconds: 4.331625,
        src: "examples/controllers/gm1/gm1_02_173.wav",
      },
      {
        sourceId: "gm1_02_035",
        controller: "gm1",
        text: "Aero lloyd five one seven turn left heading three six zero.",
        durationSeconds: 3.65325,
        src: "examples/controllers/gm1/gm1_02_035.wav",
      },
      {
        sourceId: "gm1_02_091",
        controller: "gm1",
        text: "Berlin five zero eight one climb to flight level three five zero.",
        durationSeconds: 3.6925625,
        src: "examples/controllers/gm1/gm1_02_091.wav",
      },
      {
        sourceId: "gm1_02_099",
        controller: "gm1",
        text: "Alitalia two three four contact reims on one three two two seven good bye.",
        durationSeconds: 5.90625,
        src: "examples/controllers/gm1/gm1_02_099.wav",
      },
      {
        sourceId: "gm1_02_020",
        controller: "gm1",
        text: "Aero lloyd five one seven continue present heading due to traffic.",
        durationSeconds: 4.3976875,
        src: "examples/controllers/gm1/gm1_02_020.wav",
      },
      {
        sourceId: "gm1_02_008",
        controller: "gm1",
        text: "Alitalia three zero one bonjour cleared passeiry torino flight level three three zero.",
        durationSeconds: 6.1715,
        src: "examples/controllers/gm1/gm1_02_008.wav",
      },
      {
        sourceId: "gm1_02_056",
        controller: "gm1",
        text: "Ascot nine three one nine identified cleared st prex rolampont flight level three four zero.",
        durationSeconds: 5.2419375,
        src: "examples/controllers/gm1/gm1_02_056.wav",
      },
      {
        sourceId: "gm1_02_059",
        controller: "gm1",
        text: "Aero lloyd five six zero bonjour cleared ah passeiry bilsa flight level three three zero.",
        durationSeconds: 6.4111875,
        src: "examples/controllers/gm1/gm1_02_059.wav",
      },
      {
        sourceId: "gm1_02_145",
        controller: "gm1",
        text: "L t u seven seven five six turn left heading ah two one zero climb to flight level three five zero.",
        durationSeconds: 5.8098125,
        src: "examples/controllers/gm1/gm1_02_145.wav",
      },
      {
        sourceId: "gm1_02_118",
        controller: "gm1",
        text: "Europa three eight one contact zurich on one two five decimal eight five good bye.",
        durationSeconds: 4.62575,
        src: "examples/controllers/gm1/gm1_02_118.wav",
      },
      {
        sourceId: "gm1_02_112",
        controller: "gm1",
        text: "Europa three eight one own navigation direct to willisau.",
        durationSeconds: 3.6066875,
        src: "examples/controllers/gm1/gm1_02_112.wav",
      },
      {
        sourceId: "gm1_02_023",
        controller: "gm1",
        text: "Hapag lloyd one nine five bonjour cleared ah direct to bilsa flight level three three zero.",
        durationSeconds: 5.8720625,
        src: "examples/controllers/gm1/gm1_02_023.wav",
      },
      {
        sourceId: "gm1_02_013",
        controller: "gm1",
        text: "Aero lloyd five one seven bonjour cleared kines st prex willisau flight level three two zero.",
        durationSeconds: 5.90925,
        src: "examples/controllers/gm1/gm1_02_013.wav",
      },
      {
        sourceId: "gm1_02_132",
        controller: "gm1",
        text: "Cross air two six nine zero contact marseille on one two five decimal eight five good bye.",
        durationSeconds: 4.6940625,
        src: "examples/controllers/gm1/gm1_02_132.wav",
      },
      {
        sourceId: "gm1_02_085",
        controller: "gm1",
        text: "Period one seven one bonjour maintain three three zero passeiry bilsa.",
        durationSeconds: 4.172375,
        src: "examples/controllers/gm1/gm1_02_085.wav",
      },
      {
        sourceId: "gm1_02_065",
        controller: "gm1",
        text: "Transavia three two five six ah bonjour what's your position.",
        durationSeconds: 4.361125,
        src: "examples/controllers/gm1/gm1_02_065.wav",
      },
      {
        sourceId: "gm1_02_135",
        controller: "gm1",
        text: "Foxtrot tango lima descend to flight level two seven zero.",
        durationSeconds: 3.80375,
        src: "examples/controllers/gm1/gm1_02_135.wav",
      },
      {
        sourceId: "gm1_02_125",
        controller: "gm1",
        text: "Triple five zero contact marseille one two five eight five good bye.",
        durationSeconds: 5.50225,
        src: "examples/controllers/gm1/gm1_02_125.wav",
      },
      {
        sourceId: "gm1_02_058",
        controller: "gm1",
        text: "Europa three eight one turn left heading zero zero five.",
        durationSeconds: 3.2791875,
        src: "examples/controllers/gm1/gm1_02_058.wav",
      },
      {
        sourceId: "gm1_02_043",
        controller: "gm1",
        text: "German air force three three four bonjour maintain flight level three two zero via passeiry epinal.",
        durationSeconds: 5.629375,
        src: "examples/controllers/gm1/gm1_02_043.wav",
      },
      {
        sourceId: "gm1_02_077",
        controller: "gm1",
        text: "Stand by i'll call you back for higher.",
        durationSeconds: 2.3173125,
        src: "examples/controllers/gm1/gm1_02_077.wav",
      },
      {
        sourceId: "gm1_02_092",
        controller: "gm1",
        text: "Cross air five one two ah zurich one two five eight five.",
        durationSeconds: 6.142125,
        src: "examples/controllers/gm1/gm1_02_092.wav",
      },
      {
        sourceId: "gm1_02_108",
        controller: "gm1",
        text: "France six seven three bonjour squawk five seven four four.",
        durationSeconds: 3.93575,
        src: "examples/controllers/gm1/gm1_02_108.wav",
      },
      {
        sourceId: "gm1_02_140",
        controller: "gm1",
        text: "Foxtrot tango lima contact milano one two five eight five good bye.",
        durationSeconds: 4.6470625,
        src: "examples/controllers/gm1/gm1_02_140.wav",
      },
      {
        sourceId: "gm1_02_040",
        controller: "gm1",
        text: "Europa three eight one bonjour cleared kines st prex willisau flight level three four zero.",
        durationSeconds: 5.0003125,
        src: "examples/controllers/gm1/gm1_02_040.wav",
      },
      {
        sourceId: "gm1_02_111",
        controller: "gm1",
        text: "Ascot nine three one nine contact reims on one three two decimal two seven good bye.",
        durationSeconds: 4.96375,
        src: "examples/controllers/gm1/gm1_02_111.wav",
      },
      {
        sourceId: "gm1_02_096",
        controller: "gm1",
        text: "Saudia one five five descend to flight level three zero zero.",
        durationSeconds: 3.888125,
        src: "examples/controllers/gm1/gm1_02_096.wav",
      },
    ],
    gm2: [
      {
        sourceId: "gm2_02_052",
        controller: "gm2",
        text: "Belgian airforce three three four bonjour identified cleared direct arbos then epinal flight level three two zero.",
        durationSeconds: 5.1990625,
        src: "examples/controllers/gm2/gm2_02_052.wav",
      },
      {
        sourceId: "gm2_02_103",
        controller: "gm2",
        text: "Aero lloyd five six zero cleared direct bilsa.",
        durationSeconds: 2.635625,
        src: "examples/controllers/gm2/gm2_02_103.wav",
      },
      {
        sourceId: "gm2_02_034",
        controller: "gm2",
        text: "Speedbird five eight zero descend to flight level two seven zero.",
        durationSeconds: 3.1488125,
        src: "examples/controllers/gm2/gm2_02_034.wav",
      },
      {
        sourceId: "gm2_02_056",
        controller: "gm2",
        text: "Topswiss four five seven eight contact marseille one two five decimal eight five au revoir.",
        durationSeconds: 4.458,
        src: "examples/controllers/gm2/gm2_02_056.wav",
      },
      {
        sourceId: "gm2_02_162",
        controller: "gm2",
        text: "Alitalia three one seven bonjour identified cleared passeiry torino flight level two nine zero.",
        durationSeconds: 5.130625,
        src: "examples/controllers/gm2/gm2_02_162.wav",
      },
      {
        sourceId: "gm2_02_158",
        controller: "gm2",
        text: "L t u seven seven five six climb to flight level three zero zero.",
        durationSeconds: 3.35425,
        src: "examples/controllers/gm2/gm2_02_158.wav",
      },
      {
        sourceId: "gm2_02_164",
        controller: "gm2",
        text: "Hapag lloyd one seven one contact marseille one two five decimal eight five au revoir.",
        durationSeconds: 4.08725,
        src: "examples/controllers/gm2/gm2_02_164.wav",
      },
      {
        sourceId: "gm2_02_186",
        controller: "gm2",
        text: "Alitalia three one seven do you request three three zero.",
        durationSeconds: 2.5219375,
        src: "examples/controllers/gm2/gm2_02_186.wav",
      },
      {
        sourceId: "gm2_02_090",
        controller: "gm2",
        text: "Aero lloyd five one seven contact zurich one three four decimal six au revoir.",
        durationSeconds: 3.7604375,
        src: "examples/controllers/gm2/gm2_02_090.wav",
      },
      {
        sourceId: "gm2_02_214",
        controller: "gm2",
        text: "Alitalia three one seven contact milano one two five decimal eight five au revoir.",
        durationSeconds: 4.31975,
        src: "examples/controllers/gm2/gm2_02_214.wav",
      },
      {
        sourceId: "gm2_02_096",
        controller: "gm2",
        text: "Hapag lloyd six five three bonjour identified cleared direct passeiry then bilsa flight level three four zero.",
        durationSeconds: 6.5038125,
        src: "examples/controllers/gm2/gm2_02_096.wav",
      },
      {
        sourceId: "gm2_02_035",
        controller: "gm2",
        text: "And contact milano one two five decimal eight five au revoir.",
        durationSeconds: 3.70275,
        src: "examples/controllers/gm2/gm2_02_035.wav",
      },
      {
        sourceId: "gm2_02_127",
        controller: "gm2",
        text: "Air berlin five zero eight one climb to flight level three seven zero.",
        durationSeconds: 3.420375,
        src: "examples/controllers/gm2/gm2_02_127.wav",
      },
      {
        sourceId: "gm2_02_013",
        controller: "gm2",
        text: "Tango charlie juliett contact milano one two five decimal eight five au revoir.",
        durationSeconds: 4.3108125,
        src: "examples/controllers/gm2/gm2_02_013.wav",
      },
      {
        sourceId: "gm2_02_047",
        controller: "gm2",
        text: "Alitalia three zero one descend to flight level three one zero due traffic.",
        durationSeconds: 4.5610625,
        src: "examples/controllers/gm2/gm2_02_047.wav",
      },
      {
        sourceId: "gm2_02_054",
        controller: "gm2",
        text: "Sabena nine seven zero climb to flight level three five zero.",
        durationSeconds: 3.5936875,
        src: "examples/controllers/gm2/gm2_02_054.wav",
      },
      {
        sourceId: "gm2_02_130",
        controller: "gm2",
        text: "Europa three eight one descend to flight level two eight zero ah expedite descent.",
        durationSeconds: 4.022125,
        src: "examples/controllers/gm2/gm2_02_130.wav",
      },
      {
        sourceId: "gm2_02_072",
        controller: "gm2",
        text: "Cross air six eight zero contact marseille one two five decimal eight five au revoir.",
        durationSeconds: 4.43225,
        src: "examples/controllers/gm2/gm2_02_072.wav",
      },
      {
        sourceId: "gm2_02_009",
        controller: "gm2",
        text: "Topswiss four five seven eight geneva.",
        durationSeconds: 2.2421875,
        src: "examples/controllers/gm2/gm2_02_009.wav",
      },
      {
        sourceId: "gm2_02_088",
        controller: "gm2",
        text: "Lufthansa eight two six eight climb initially level three four zero.",
        durationSeconds: 3.7763125,
        src: "examples/controllers/gm2/gm2_02_088.wav",
      },
      {
        sourceId: "gm2_02_071",
        controller: "gm2",
        text: "Fox echo xray six six cleared direct torino.",
        durationSeconds: 2.9450625,
        src: "examples/controllers/gm2/gm2_02_071.wav",
      },
      {
        sourceId: "gm2_02_204",
        controller: "gm2",
        text: "November one four five whiskey contact radar one two eight decimal one five au revoir.",
        durationSeconds: 3.9678125,
        src: "examples/controllers/gm2/gm2_02_204.wav",
      },
      {
        sourceId: "gm2_02_139",
        controller: "gm2",
        text: "Air berlin five zero eight one.",
        durationSeconds: 1.5141875,
        src: "examples/controllers/gm2/gm2_02_139.wav",
      },
      {
        sourceId: "gm2_02_033",
        controller: "gm2",
        text: "Luxair five five one cleared direct torino.",
        durationSeconds: 2.53525,
        src: "examples/controllers/gm2/gm2_02_033.wav",
      },
      {
        sourceId: "gm2_02_082",
        controller: "gm2",
        text: "Cross air two six nine zero bonjour squawk ident.",
        durationSeconds: 3.1766875,
        src: "examples/controllers/gm2/gm2_02_082.wav",
      },
      {
        sourceId: "gm2_02_117",
        controller: "gm2",
        text: "German air force four nine zero one bonjour identified maintain flight level three three zero report heading.",
        durationSeconds: 5.2379375,
        src: "examples/controllers/gm2/gm2_02_117.wav",
      },
      {
        sourceId: "gm2_02_193",
        controller: "gm2",
        text: "Alitalia three one seven climb to flight level three two zero.",
        durationSeconds: 3.642,
        src: "examples/controllers/gm2/gm2_02_193.wav",
      },
      {
        sourceId: "gm2_02_058",
        controller: "gm2",
        text: "Yeah should be with ah one two eight one five i think.",
        durationSeconds: 2.5313125,
        src: "examples/controllers/gm2/gm2_02_058.wav",
      },
      {
        sourceId: "gm2_02_123",
        controller: "gm2",
        text: "Air berlin five zero eight one proceed to la tour du pin.",
        durationSeconds: 2.5785625,
        src: "examples/controllers/gm2/gm2_02_123.wav",
      },
      {
        sourceId: "gm2_02_140",
        controller: "gm2",
        text: "Contact geneva one two eight decimal one five au revoir.",
        durationSeconds: 2.8015,
        src: "examples/controllers/gm2/gm2_02_140.wav",
      },
      {
        sourceId: "gm2_02_205",
        controller: "gm2",
        text: "Monarch two four four contact reims one three two decimal two seven au revoir.",
        durationSeconds: 3.94,
        src: "examples/controllers/gm2/gm2_02_205.wav",
      },
      {
        sourceId: "gm2_02_086",
        controller: "gm2",
        text: "Hapag lloyd one nine five contact marseille one two five decimal eight five au revoir.",
        durationSeconds: 4.12275,
        src: "examples/controllers/gm2/gm2_02_086.wav",
      },
      {
        sourceId: "gm2_02_126",
        controller: "gm2",
        text: "Europa three eight one bonjour expect descent shortly.",
        durationSeconds: 2.577,
        src: "examples/controllers/gm2/gm2_02_126.wav",
      },
      {
        sourceId: "gm2_02_003",
        controller: "gm2",
        text: "Swissair six six zero romeo contact marseille one two five decimal eight five au revoir.",
        durationSeconds: 4.4934375,
        src: "examples/controllers/gm2/gm2_02_003.wav",
      },
      {
        sourceId: "gm2_02_004",
        controller: "gm2",
        text: "Luxair five five one ah confirm level three three zero.",
        durationSeconds: 4.1211875,
        src: "examples/controllers/gm2/gm2_02_004.wav",
      },
      {
        sourceId: "gm2_02_078",
        controller: "gm2",
        text: "Hamburg air two five four six bonjour identified cleared passeiry la tour du pin flight level three zero zero.",
        durationSeconds: 5.5404375,
        src: "examples/controllers/gm2/gm2_02_078.wav",
      },
      {
        sourceId: "gm2_02_135",
        controller: "gm2",
        text: "Hapag lloyd one seven one cleared direct bilsa.",
        durationSeconds: 2.3498125,
        src: "examples/controllers/gm2/gm2_02_135.wav",
      },
      {
        sourceId: "gm2_02_041",
        controller: "gm2",
        text: "Sabena nine seven zero report heading.",
        durationSeconds: 2.0809375,
        src: "examples/controllers/gm2/gm2_02_041.wav",
      },
      {
        sourceId: "gm2_02_183",
        controller: "gm2",
        text: "Airfrans six four zero bonjour identified cleared passeiry torino flight level two nine zero.",
        durationSeconds: 4.6679375,
        src: "examples/controllers/gm2/gm2_02_183.wav",
      },
      {
        sourceId: "gm2_02_066",
        controller: "gm2",
        text: "Luxair five five one contact milano one two five decimal eight five au revoir.",
        durationSeconds: 4.3061875,
        src: "examples/controllers/gm2/gm2_02_066.wav",
      },
      {
        sourceId: "gm2_02_057",
        controller: "gm2",
        text: "Alitalia three zero one contact milano one two five decimal eight five au revoir.",
        durationSeconds: 4.425,
        src: "examples/controllers/gm2/gm2_02_057.wav",
      },
      {
        sourceId: "gm2_02_083",
        controller: "gm2",
        text: "Cross air two six nine zero identified climb to flight level two seven zero and report heading.",
        durationSeconds: 6.2188125,
        src: "examples/controllers/gm2/gm2_02_083.wav",
      },
      {
        sourceId: "gm2_02_211",
        controller: "gm2",
        text: "Sabena eight one one bonjour identified cleared valda passeiry torino flight level three three zero.",
        durationSeconds: 5.9715,
        src: "examples/controllers/gm2/gm2_02_211.wav",
      },
      {
        sourceId: "gm2_02_195",
        controller: "gm2",
        text: "L t u seven seven five six contact radar one two eight decimal one five au revoir.",
        durationSeconds: 4.9375625,
        src: "examples/controllers/gm2/gm2_02_195.wav",
      },
      {
        sourceId: "gm2_02_172",
        controller: "gm2",
        text: "I don't think either.",
        durationSeconds: 1.8974375,
        src: "examples/controllers/gm2/gm2_02_172.wav",
      },
      {
        sourceId: "gm2_02_120",
        controller: "gm2",
        text: "Zulu bravo bravo contact milano one two five decimal eight five au revoir.",
        durationSeconds: 4.4861875,
        src: "examples/controllers/gm2/gm2_02_120.wav",
      },
      {
        sourceId: "gm2_02_027",
        controller: "gm2",
        text: "Speedbird five eight zero geneva.",
        durationSeconds: 1.652,
        src: "examples/controllers/gm2/gm2_02_027.wav",
      },
    ],
    sm1: [
      {
        sourceId: "sm1_05_086",
        controller: "sm1",
        text: "Alitalia four zero one maintain your present heading and climb flight level three three zero.",
        durationSeconds: 6.5146875,
        src: "examples/controllers/sm1/sm1_05_086.wav",
      },
      {
        sourceId: "sm1_02_113",
        controller: "sm1",
        text: "Turkish five one five rhein radar one two seven three seven.",
        durationSeconds: 3.756,
        src: "examples/controllers/sm1/sm1_02_113.wav",
      },
      {
        sourceId: "sm1_02_041",
        controller: "sm1",
        text: "German air force five eight five set course direct frankfurt.",
        durationSeconds: 3.272375,
        src: "examples/controllers/sm1/sm1_02_041.wav",
      },
      {
        sourceId: "sm1_06_044",
        controller: "sm1",
        text: "German air force five eight five rhein radar stand by for identification.",
        durationSeconds: 5.0298125,
        src: "examples/controllers/sm1/sm1_06_044.wav",
      },
      {
        sourceId: "sm1_02_107",
        controller: "sm1",
        text: "Sierra alfa fox one one two descend flight level three two zero.",
        durationSeconds: 4.3761875,
        src: "examples/controllers/sm1/sm1_02_107.wav",
      },
      {
        sourceId: "sm1_02_151",
        controller: "sm1",
        text: "Alitalia one four nine direct tango romeo alfa.",
        durationSeconds: 3.711625,
        src: "examples/controllers/sm1/sm1_02_151.wav",
      },
      {
        sourceId: "sm1_01_015",
        controller: "sm1",
        text: "Foxtrot sierra india rhein identified climb flight level two six zero.",
        durationSeconds: 4.8634375,
        src: "examples/controllers/sm1/sm1_01_015.wav",
      },
      {
        sourceId: "sm1_01_061",
        controller: "sm1",
        text: "Sobelair two five five seven maintain heading contact rhein one three two decimal four.",
        durationSeconds: 5.1871875,
        src: "examples/controllers/sm1/sm1_01_061.wav",
      },
      {
        sourceId: "sm1_07_057",
        controller: "sm1",
        text: "Sabena seven eight one six rhein radar you are identified.",
        durationSeconds: 4.2564375,
        src: "examples/controllers/sm1/sm1_07_057.wav",
      },
      {
        sourceId: "sm1_02_008",
        controller: "sm1",
        text: "Hapag lloyd six five three report rate of climb.",
        durationSeconds: 3.085875,
        src: "examples/controllers/sm1/sm1_02_008.wav",
      },
      {
        sourceId: "sm1_05_129",
        controller: "sm1",
        text: "Britannia two three six alfa rhein radar identified.",
        durationSeconds: 3.3024375,
        src: "examples/controllers/sm1/sm1_05_129.wav",
      },
      {
        sourceId: "sm1_02_078",
        controller: "sm1",
        text: "Sierra alfa foxtrot one one two non r v s m you are identified.",
        durationSeconds: 5.8031875,
        src: "examples/controllers/sm1/sm1_02_078.wav",
      },
      {
        sourceId: "sm1_01_076",
        controller: "sm1",
        text: "Lufthansa four six five two rhein radar identified climb flight level two nine zero set course trasadingen.",
        durationSeconds: 6.3491875,
        src: "examples/controllers/sm1/sm1_01_076.wav",
      },
      {
        sourceId: "sm1_05_056",
        controller: "sm1",
        text: "K l m two six four squawk ident.",
        durationSeconds: 2.73775,
        src: "examples/controllers/sm1/sm1_05_056.wav",
      },
      {
        sourceId: "sm1_04_097",
        controller: "sm1",
        text: "Lufthansa four four one six climb flight level two eight zero.",
        durationSeconds: 4.4249375,
        src: "examples/controllers/sm1/sm1_04_097.wav",
      },
      {
        sourceId: "sm1_07_142",
        controller: "sm1",
        text: "Speedbird two two three contact rhein one two seven three seven.",
        durationSeconds: 3.5815,
        src: "examples/controllers/sm1/sm1_07_142.wav",
      },
      {
        sourceId: "sm1_05_016",
        controller: "sm1",
        text: "Speedbird one five six rhein radar one two seven three seven.",
        durationSeconds: 3.4125,
        src: "examples/controllers/sm1/sm1_05_016.wav",
      },
      {
        sourceId: "sm1_05_075",
        controller: "sm1",
        text: "K l m three hundred kilo rhein radar one two seven decimal three seven.",
        durationSeconds: 3.6949375,
        src: "examples/controllers/sm1/sm1_05_075.wav",
      },
      {
        sourceId: "sm1_06_086",
        controller: "sm1",
        text: "Lufthansa four four one six proceed to trasadingen.",
        durationSeconds: 3.87475,
        src: "examples/controllers/sm1/sm1_06_086.wav",
      },
      {
        sourceId: "sm1_07_148",
        controller: "sm1",
        text: "Midland seven two zero how do you read.",
        durationSeconds: 2.5181875,
        src: "examples/controllers/sm1/sm1_07_148.wav",
      },
      {
        sourceId: "sm1_01_005",
        controller: "sm1",
        text: "Transwede one zero one rhein identified set course trasadingen.",
        durationSeconds: 3.9115625,
        src: "examples/controllers/sm1/sm1_01_005.wav",
      },
      {
        sourceId: "sm1_04_072",
        controller: "sm1",
        text: "Buongiorno alitalia one one nine rhein radar identified.",
        durationSeconds: 3.6021875,
        src: "examples/controllers/sm1/sm1_04_072.wav",
      },
      {
        sourceId: "sm1_07_140",
        controller: "sm1",
        text: "Speedbird one two two rhein identified confirm level four hundred.",
        durationSeconds: 3.59275,
        src: "examples/controllers/sm1/sm1_07_140.wav",
      },
      {
        sourceId: "sm1_07_145",
        controller: "sm1",
        text: "Negative speedbird two three three contact rhein one two seven three seven.",
        durationSeconds: 5.1796875,
        src: "examples/controllers/sm1/sm1_07_145.wav",
      },
      {
        sourceId: "sm1_07_133",
        controller: "sm1",
        text: "Identified.",
        durationSeconds: 1.0965,
        src: "examples/controllers/sm1/sm1_07_133.wav",
      },
      {
        sourceId: "sm1_01_028",
        controller: "sm1",
        text: "Foxtrot sierra india turn left heading one seven five climb flight level three seven zero.",
        durationSeconds: 6.0346875,
        src: "examples/controllers/sm1/sm1_01_028.wav",
      },
      {
        sourceId: "sm1_06_073",
        controller: "sm1",
        text: "Alitalia four eight seven roger identified.",
        durationSeconds: 5.819375,
        src: "examples/controllers/sm1/sm1_06_073.wav",
      },
      {
        sourceId: "sm1_04_025",
        controller: "sm1",
        text: "Foxtrot sierra india climb flight level two nine zero.",
        durationSeconds: 3.9010625,
        src: "examples/controllers/sm1/sm1_04_025.wav",
      },
      {
        sourceId: "sm1_06_011",
        controller: "sm1",
        text: "Onur air nine eight nine turn ten degrees right and climb flight level three three zero.",
        durationSeconds: 4.8285,
        src: "examples/controllers/sm1/sm1_06_011.wav",
      },
      {
        sourceId: "sm1_06_054",
        controller: "sm1",
        text: "Alitalia one one seven rhein.",
        durationSeconds: 1.840625,
        src: "examples/controllers/sm1/sm1_06_054.wav",
      },
      {
        sourceId: "sm1_07_087",
        controller: "sm1",
        text: "Netherlands four one four turn left to trasadingen.",
        durationSeconds: 3.3715,
        src: "examples/controllers/sm1/sm1_07_087.wav",
      },
      {
        sourceId: "sm1_07_018",
        controller: "sm1",
        text: "Swissair nine three five two contact rhein one two seven decimal three seven.",
        durationSeconds: 3.865625,
        src: "examples/controllers/sm1/sm1_07_018.wav",
      },
      {
        sourceId: "sm1_04_153",
        controller: "sm1",
        text: "Sabena eight zero one turn right ten degrees.",
        durationSeconds: 2.72025,
        src: "examples/controllers/sm1/sm1_04_153.wav",
      },
      {
        sourceId: "sm1_07_062",
        controller: "sm1",
        text: "Aero lloyd five two eight contact zurich on one three three decimal four.",
        durationSeconds: 4.590125,
        src: "examples/controllers/sm1/sm1_07_062.wav",
      },
      {
        sourceId: "sm1_02_081",
        controller: "sm1",
        text: "Lufthansa four four one six ah rhein identified turn right by one five degrees.",
        durationSeconds: 5.7123125,
        src: "examples/controllers/sm1/sm1_02_081.wav",
      },
      {
        sourceId: "sm1_06_150",
        controller: "sm1",
        text: "Lufthansa four three seven six contact zurich one three four decimal six.",
        durationSeconds: 5.17,
        src: "examples/controllers/sm1/sm1_06_150.wav",
      },
      {
        sourceId: "sm1_06_095",
        controller: "sm1",
        text: "Sierra fox alfa one one two contact rhein one two seven decimal three seven.",
        durationSeconds: 4.82525,
        src: "examples/controllers/sm1/sm1_06_095.wav",
      },
      {
        sourceId: "sm1_07_056",
        controller: "sm1",
        text: "German air force five eight five non r v s m rhein radar identified.",
        durationSeconds: 4.103625,
        src: "examples/controllers/sm1/sm1_07_056.wav",
      },
      {
        sourceId: "sm1_05_164",
        controller: "sm1",
        text: "Alitalia two nine two rhein one two seven decimal three seven.",
        durationSeconds: 4.427,
        src: "examples/controllers/sm1/sm1_05_164.wav",
      },
      {
        sourceId: "sm1_05_094",
        controller: "sm1",
        text: "Lufthansa four four one six rhein radar identified left by ten degrees call you back for higher.",
        durationSeconds: 5.2839375,
        src: "examples/controllers/sm1/sm1_05_094.wav",
      },
      {
        sourceId: "sm1_04_007",
        controller: "sm1",
        text: "Lufthansa eight two six eight set course to hochwald thereafter st prex.",
        durationSeconds: 5.0554375,
        src: "examples/controllers/sm1/sm1_04_007.wav",
      },
      {
        sourceId: "sm1_06_089",
        controller: "sm1",
        text: "German air force five eight five contact rhein on one two seven three seven.",
        durationSeconds: 3.88775,
        src: "examples/controllers/sm1/sm1_06_089.wav",
      },
      {
        sourceId: "sm1_01_074",
        controller: "sm1",
        text: "Viva five eight five request heading.",
        durationSeconds: 2.704375,
        src: "examples/controllers/sm1/sm1_01_074.wav",
      },
      {
        sourceId: "sm1_02_086",
        controller: "sm1",
        text: "P s a four zero two hotel guten tag identified.",
        durationSeconds: 2.9156875,
        src: "examples/controllers/sm1/sm1_02_086.wav",
      },
      {
        sourceId: "sm1_01_012",
        controller: "sm1",
        text: "Lufthansa eight two six eight rhein identified set course trasadingen climb flight level two seven zero.",
        durationSeconds: 7.2105,
        src: "examples/controllers/sm1/sm1_01_012.wav",
      },
      {
        sourceId: "sm1_07_011",
        controller: "sm1",
        text: "Lufthansa eight two six eight proceed to trasa.",
        durationSeconds: 3.47275,
        src: "examples/controllers/sm1/sm1_07_011.wav",
      },
      {
        sourceId: "sm1_07_051",
        controller: "sm1",
        text: "Georgia zero three seven contact rhein one two seven decimal three seven.",
        durationSeconds: 3.589,
        src: "examples/controllers/sm1/sm1_07_051.wav",
      },
      {
        sourceId: "sm1_05_091",
        controller: "sm1",
        text: "K l m two six four turn left to ah nattenheim.",
        durationSeconds: 4.60775,
        src: "examples/controllers/sm1/sm1_05_091.wav",
      },
      {
        sourceId: "sm1_05_110",
        controller: "sm1",
        text: "Four four one six is cleared flight level two nine zero.",
        durationSeconds: 3.1334375,
        src: "examples/controllers/sm1/sm1_05_110.wav",
      },
      {
        sourceId: "sm1_06_105",
        controller: "sm1",
        text: "Europa three six three rhein identified proceed direct frankfurt.",
        durationSeconds: 3.742875,
        src: "examples/controllers/sm1/sm1_06_105.wav",
      },
    ],
    zf2: [
      {
        sourceId: "zf2_01_114",
        controller: "zf2",
        text: "Swissair four eight eight good morning radar contact call you back with higher.",
        durationSeconds: 3.6905,
        src: "examples/controllers/zf2/zf2_01_114.wav",
      },
      {
        sourceId: "zf2_02_032",
        controller: "zf2",
        text: "Jetcom one three three good morning radar contact climb flight level three four zero with the best rate of climb.",
        durationSeconds: 6.61725,
        src: "examples/controllers/zf2/zf2_02_032.wav",
      },
      {
        sourceId: "zf2_04_094",
        controller: "zf2",
        text: "Lufthansa four seven two three contact now milan on one three four five two.",
        durationSeconds: 5.3958125,
        src: "examples/controllers/zf2/zf2_04_094.wav",
      },
      {
        sourceId: "zf2_05_084",
        controller: "zf2",
        text: "Lufthansa four seven zero zero good afternoon radar contact trasadingen st prex.",
        durationSeconds: 4.9325625,
        src: "examples/controllers/zf2/zf2_05_084.wav",
      },
      {
        sourceId: "zf2_05_006",
        controller: "zf2",
        text: "Alitalia one five eight radar contact call you back with direct.",
        durationSeconds: 3.5343125,
        src: "examples/controllers/zf2/zf2_05_006.wav",
      },
      {
        sourceId: "zf2_01_070",
        controller: "zf2",
        text: "Air inter three two zero papa hotel.",
        durationSeconds: 2.2898125,
        src: "examples/controllers/zf2/zf2_01_070.wav",
      },
      {
        sourceId: "zf2_04_140",
        controller: "zf2",
        text: "L t u seven seven five six geneva one three three one five bye.",
        durationSeconds: 3.5604375,
        src: "examples/controllers/zf2/zf2_04_140.wav",
      },
      {
        sourceId: "zf2_06_056",
        controller: "zf2",
        text: "Good morning l t u one six zero two radar contact climb initially flight level two nine zero.",
        durationSeconds: 5.1601875,
        src: "examples/controllers/zf2/zf2_06_056.wav",
      },
      {
        sourceId: "zf2_06_141",
        controller: "zf2",
        text: "Air malta four five zero contact rhein control one three two decimal four.",
        durationSeconds: 4.0704375,
        src: "examples/controllers/zf2/zf2_06_141.wav",
      },
      {
        sourceId: "zf2_01_169",
        controller: "zf2",
        text: "Alright please milan one three four five two bye bye.",
        durationSeconds: 2.4479375,
        src: "examples/controllers/zf2/zf2_01_169.wav",
      },
      {
        sourceId: "zf2_03_227",
        controller: "zf2",
        text: "Europa three six one.",
        durationSeconds: 1.6150625,
        src: "examples/controllers/zf2/zf2_03_227.wav",
      },
      {
        sourceId: "zf2_06_044",
        controller: "zf2",
        text: "Good afternoon speedway three three five two radar contact proceed zurich east fusse.",
        durationSeconds: 4.702125,
        src: "examples/controllers/zf2/zf2_06_044.wav",
      },
      {
        sourceId: "zf2_03_082",
        controller: "zf2",
        text: "Good morning swissair six five five two radar contact climb flight level two nine zero proceed direct zurich east fusse.",
        durationSeconds: 6.6076875,
        src: "examples/controllers/zf2/zf2_03_082.wav",
      },
      {
        sourceId: "zf2_03_095",
        controller: "zf2",
        text: "Aero lloyd five one seven good morning maintain flight level three two zero proceed via willisau and trasadingen karlsruhe.",
        durationSeconds: 9.015,
        src: "examples/controllers/zf2/zf2_03_095.wav",
      },
      {
        sourceId: "zf2_03_067",
        controller: "zf2",
        text: "Transwede three five seven one contact reims one three four decimal four bye bye.",
        durationSeconds: 4.20225,
        src: "examples/controllers/zf2/zf2_03_067.wav",
      },
      {
        sourceId: "zf2_01_184",
        controller: "zf2",
        text: "Speedway three four six nine contact milan one three four five two.",
        durationSeconds: 3.3781875,
        src: "examples/controllers/zf2/zf2_01_184.wav",
      },
      {
        sourceId: "zf2_03_252",
        controller: "zf2",
        text: "Jetaviation seven zero one turn left heading of two five five.",
        durationSeconds: 3.6755625,
        src: "examples/controllers/zf2/zf2_03_252.wav",
      },
      {
        sourceId: "zf2_01_258",
        controller: "zf2",
        text: "Alitalia one one nine descend flight level two five zero rate ah two thousand until two seven zero descending.",
        durationSeconds: 5.482625,
        src: "examples/controllers/zf2/zf2_01_258.wav",
      },
      {
        sourceId: "zf2_03_049",
        controller: "zf2",
        text: "Lufthansa eight two six eight climb flight level three five zero.",
        durationSeconds: 3.751625,
        src: "examples/controllers/zf2/zf2_03_049.wav",
      },
      {
        sourceId: "zf2_03_123",
        controller: "zf2",
        text: "Airfrans three five six turn left heading of two five zero.",
        durationSeconds: 3.5808125,
        src: "examples/controllers/zf2/zf2_03_123.wav",
      },
      {
        sourceId: "zf2_03_058",
        controller: "zf2",
        text: "Transwede three five seven one direct luxeuil.",
        durationSeconds: 2.695,
        src: "examples/controllers/zf2/zf2_03_058.wav",
      },
      {
        sourceId: "zf2_06_125",
        controller: "zf2",
        text: "Airfrans six seven zero good afternoon i'll call you back with lower.",
        durationSeconds: 3.1595625,
        src: "examples/controllers/zf2/zf2_06_125.wav",
      },
      {
        sourceId: "zf2_06_071",
        controller: "zf2",
        text: "And lufthansa three six zero four now you're recleared three three zero to be final level then.",
        durationSeconds: 5.09025,
        src: "examples/controllers/zf2/zf2_06_071.wav",
      },
      {
        sourceId: "zf2_02_177",
        controller: "zf2",
        text: "Shamrock four eight two two contact milan one three four decimal five two bye bye.",
        durationSeconds: 4.4173125,
        src: "examples/controllers/zf2/zf2_02_177.wav",
      },
      {
        sourceId: "zf2_06_119",
        controller: "zf2",
        text: "Portugalia five four three geneva one three three one five bye.",
        durationSeconds: 3.709125,
        src: "examples/controllers/zf2/zf2_06_119.wav",
      },
      {
        sourceId: "zf2_03_212",
        controller: "zf2",
        text: "Alitalia one one seven descend flight level two seven zero.",
        durationSeconds: 3.4661875,
        src: "examples/controllers/zf2/zf2_03_212.wav",
      },
      {
        sourceId: "zf2_05_209",
        controller: "zf2",
        text: "Cross air five one eight contact rhein control on one three two decimal four bye.",
        durationSeconds: 3.835125,
        src: "examples/controllers/zf2/zf2_05_209.wav",
      },
      {
        sourceId: "zf2_04_155",
        controller: "zf2",
        text: "Cotam one four one contact milan one three four five two bye.",
        durationSeconds: 3.74025,
        src: "examples/controllers/zf2/zf2_04_155.wav",
      },
      {
        sourceId: "zf2_03_007",
        controller: "zf2",
        text: "Shamrock four eight six four contact rhein control on one three two decimal four bye.",
        durationSeconds: 4.2841875,
        src: "examples/controllers/zf2/zf2_03_007.wav",
      },
      {
        sourceId: "zf2_03_077",
        controller: "zf2",
        text: "Sabena seven eight one six contact rhein control on one two zero decimal nine two bye bye.",
        durationSeconds: 4.790625,
        src: "examples/controllers/zf2/zf2_03_077.wav",
      },
    ],
    zf3: [
      {
        sourceId: "zf3_03_042",
        controller: "zf3",
        text: "L t u one six zero two left again by ten degrees.",
        durationSeconds: 2.6143125,
        src: "examples/controllers/zf3/zf3_03_042.wav",
      },
      {
        sourceId: "zf3_03_133",
        controller: "zf3",
        text: "Alitalia four one six rhein one three two decimal four ciao.",
        durationSeconds: 3.4349375,
        src: "examples/controllers/zf3/zf3_03_133.wav",
      },
      {
        sourceId: "zf3_02_017",
        controller: "zf3",
        text: "Delta echo bravo continue climb to flight level three four zero.",
        durationSeconds: 3.2760625,
        src: "examples/controllers/zf3/zf3_02_017.wav",
      },
      {
        sourceId: "zf3_03_024",
        controller: "zf3",
        text: "Mission six zero one five three good morning identified route willisau trasadingen tango climb to flight level three two zero.",
        durationSeconds: 7.303625,
        src: "examples/controllers/zf3/zf3_03_024.wav",
      },
      {
        sourceId: "zf3_03_153",
        controller: "zf3",
        text: "Airfrans three two four contact reims one three four four.",
        durationSeconds: 3.095875,
        src: "examples/controllers/zf3/zf3_03_153.wav",
      },
      {
        sourceId: "zf3_02_197",
        controller: "zf3",
        text: "Austrian four one six whiskey zurich radar good afternoon identified trasadingen zurich east fusse maintain flight level three four zero.",
        durationSeconds: 6.74375,
        src: "examples/controllers/zf3/zf3_02_197.wav",
      },
      {
        sourceId: "zf3_02_193",
        controller: "zf3",
        text: "Airfrans six eight zero good afternoon descend to flight level two five zero rate of descent two thousand five hundred feet or more until passing flight level three zero zero.",
        durationSeconds: 8.38875,
        src: "examples/controllers/zf3/zf3_02_193.wav",
      },
      {
        sourceId: "zf3_02_086",
        controller: "zf3",
        text: "Airlink one three zurich radar good afternoon identified maintain flight level three zero zero trasadingen zurich east fusse.",
        durationSeconds: 6.504875,
        src: "examples/controllers/zf3/zf3_02_086.wav",
      },
      {
        sourceId: "zf3_03_012",
        controller: "zf3",
        text: "Alitalia six four seven four rhein one two zero nine two bye bye.",
        durationSeconds: 4.356875,
        src: "examples/controllers/zf3/zf3_03_012.wav",
      },
      {
        sourceId: "zf3_02_018",
        controller: "zf3",
        text: "French line nine one six three zurich radar good afternoon identified maintain flight level three three zero trasadingen zurich east fusse.",
        durationSeconds: 6.4305625,
        src: "examples/controllers/zf3/zf3_02_018.wav",
      },
      {
        sourceId: "zf3_02_022",
        controller: "zf3",
        text: "Condor triple six zurich radar good afternoon continue climb to flight level three three zero.",
        durationSeconds: 4.985375,
        src: "examples/controllers/zf3/zf3_02_022.wav",
      },
      {
        sourceId: "zf3_03_164",
        controller: "zf3",
        text: "Alitalia one three five zurich radar good morning identified trasadingen saronno maintain flight level three hundred.",
        durationSeconds: 5.659625,
        src: "examples/controllers/zf3/zf3_03_164.wav",
      },
      {
        sourceId: "zf3_03_111",
        controller: "zf3",
        text: "Lufthansa five five zero four zurich radar good morning identified maintain flight level confirm two nine zero.",
        durationSeconds: 6.7113125,
        src: "examples/controllers/zf3/zf3_03_111.wav",
      },
      {
        sourceId: "zf3_02_200",
        controller: "zf3",
        text: "Airfrans two four two six good afternoon identified trasadingen zurich east fusse maintain flight level three three zero.",
        durationSeconds: 6.12675,
        src: "examples/controllers/zf3/zf3_02_200.wav",
      },
      {
        sourceId: "zf3_03_005",
        controller: "zf3",
        text: "Bama one five good morning identified route zurich east resia maintain flight level three three zero.",
        durationSeconds: 5.023125,
        src: "examples/controllers/zf3/zf3_03_005.wav",
      },
      {
        sourceId: "zf3_03_016",
        controller: "zf3",
        text: "Lufthansa four four zero eight own navigation st prex.",
        durationSeconds: 2.8715,
        src: "examples/controllers/zf3/zf3_03_016.wav",
      },
      {
        sourceId: "zf3_02_195",
        controller: "zf3",
        text: "Israeli four four two milan one three four decimal five two.",
        durationSeconds: 4.13525,
        src: "examples/controllers/zf3/zf3_02_195.wav",
      },
      {
        sourceId: "zf3_03_172",
        controller: "zf3",
        text: "Air algerie two zero seven three good morning identified trasadingen st prex maintain two nine zero.",
        durationSeconds: 4.852875,
        src: "examples/controllers/zf3/zf3_03_172.wav",
      },
      {
        sourceId: "zf3_03_071",
        controller: "zf3",
        text: "Lufthansa four seven hundred climb to flight level three five zero.",
        durationSeconds: 2.968,
        src: "examples/controllers/zf3/zf3_03_071.wav",
      },
      {
        sourceId: "zf3_03_084",
        controller: "zf3",
        text: "Maintain three two zero.",
        durationSeconds: 1.494625,
        src: "examples/controllers/zf3/zf3_03_084.wav",
      },
      {
        sourceId: "zf3_03_059",
        controller: "zf3",
        text: "Lufthansa four seven zero zero zurich radar good morning identified maintain flight level two nine zero trasadingen st prex call you back for further climb.",
        durationSeconds: 6.799375,
        src: "examples/controllers/zf3/zf3_03_059.wav",
      },
      {
        sourceId: "zf3_02_198",
        controller: "zf3",
        text: "Yeah should you be with geneva.",
        durationSeconds: 3.2439375,
        src: "examples/controllers/zf3/zf3_02_198.wav",
      },
      {
        sourceId: "zf3_02_114",
        controller: "zf3",
        text: "Alitalia four one six continue heading three six zero i'll call you back for navigation.",
        durationSeconds: 5.5828125,
        src: "examples/controllers/zf3/zf3_02_114.wav",
      },
      {
        sourceId: "zf3_02_067",
        controller: "zf3",
        text: "Speedway three three five two call milan one three four decimal five two bye bye.",
        durationSeconds: 4.273875,
        src: "examples/controllers/zf3/zf3_02_067.wav",
      },
      {
        sourceId: "zf3_02_117",
        controller: "zf3",
        text: "What is your level.",
        durationSeconds: 0.8341875,
        src: "examples/controllers/zf3/zf3_02_117.wav",
      },
      {
        sourceId: "zf3_03_169",
        controller: "zf3",
        text: "Aero lloyd five six two good morning.",
        durationSeconds: 2.178375,
        src: "examples/controllers/zf3/zf3_03_169.wav",
      },
      {
        sourceId: "zf3_03_004",
        controller: "zf3",
        text: "Lufthansa four four zero eight zurich radar good morning identified fly heading two one zero for a shortcut maintain flight level two nine zero initially.",
        durationSeconds: 7.322,
        src: "examples/controllers/zf3/zf3_03_004.wav",
      },
      {
        sourceId: "zf3_02_066",
        controller: "zf3",
        text: "Emirates zero two four zurich radar good afternoon identified maintain flight level three four zero trasadingen zurich east fusse.",
        durationSeconds: 6.1358125,
        src: "examples/controllers/zf3/zf3_02_066.wav",
      },
      {
        sourceId: "zf3_03_047",
        controller: "zf3",
        text: "Bama one five milan one three four decimal five two bye bye.",
        durationSeconds: 3.8620625,
        src: "examples/controllers/zf3/zf3_03_047.wav",
      },
      {
        sourceId: "zf3_02_060",
        controller: "zf3",
        text: "One three four four correct yes.",
        durationSeconds: 1.7635,
        src: "examples/controllers/zf3/zf3_02_060.wav",
      },
      {
        sourceId: "zf3_02_091",
        controller: "zf3",
        text: "Reach six zero one five three contact rhein one three two decimal four.",
        durationSeconds: 4.10375,
        src: "examples/controllers/zf3/zf3_02_091.wav",
      },
      {
        sourceId: "zf3_02_192",
        controller: "zf3",
        text: "Alitalia three six nine zurich radar good afternoon identified trasadingen saronno maintain flight level three zero zero.",
        durationSeconds: 6.5863125,
        src: "examples/controllers/zf3/zf3_02_192.wav",
      },
      {
        sourceId: "zf3_03_179",
        controller: "zf3",
        text: "Merair six nine five two milan one three four five two.",
        durationSeconds: 2.9191875,
        src: "examples/controllers/zf3/zf3_03_179.wav",
      },
      {
        sourceId: "zf3_02_120",
        controller: "zf3",
        text: "Alitalia four one six own navigation to zurich east.",
        durationSeconds: 3.331625,
        src: "examples/controllers/zf3/zf3_02_120.wav",
      },
      {
        sourceId: "zf3_03_068",
        controller: "zf3",
        text: "India lima oscar oscar kilo zurich radar good morning identified maintain flight level two nine zero trasadingen saronno call you back for further climb.",
        durationSeconds: 7.0604375,
        src: "examples/controllers/zf3/zf3_03_068.wav",
      },
      {
        sourceId: "zf3_02_016",
        controller: "zf3",
        text: "Iberia three five three zero due traffic descend now to flight level two nine zero.",
        durationSeconds: 3.9230625,
        src: "examples/controllers/zf3/zf3_02_016.wav",
      },
      {
        sourceId: "zf3_02_040",
        controller: "zf3",
        text: "Correct and high rate of climb please.",
        durationSeconds: 1.9199375,
        src: "examples/controllers/zf3/zf3_02_040.wav",
      },
      {
        sourceId: "zf3_02_108",
        controller: "zf3",
        text: "Alitalia four zero four good afternoon squawk seven five three two.",
        durationSeconds: 3.2510625,
        src: "examples/controllers/zf3/zf3_02_108.wav",
      },
      {
        sourceId: "zf3_03_097",
        controller: "zf3",
        text: "Alitalia one five zero.",
        durationSeconds: 1.449,
        src: "examples/controllers/zf3/zf3_03_097.wav",
      },
      {
        sourceId: "zf3_03_079",
        controller: "zf3",
        text: "Fox sierra roger in this case descend to flight level two nine zero due crossing traffic.",
        durationSeconds: 5.488625,
        src: "examples/controllers/zf3/zf3_03_079.wav",
      },
      {
        sourceId: "zf3_03_127",
        controller: "zf3",
        text: "India oscar kilo milan one three four decimal five two ciao.",
        durationSeconds: 4.001375,
        src: "examples/controllers/zf3/zf3_03_127.wav",
      },
      {
        sourceId: "zf3_03_113",
        controller: "zf3",
        text: "Well maintain two nine zero you have to descend.",
        durationSeconds: 2.2805625,
        src: "examples/controllers/zf3/zf3_03_113.wav",
      },
      {
        sourceId: "zf3_03_043",
        controller: "zf3",
        text: "Alitalia one five eight reims one three four decimal four ciao.",
        durationSeconds: 3.9849375,
        src: "examples/controllers/zf3/zf3_03_043.wav",
      },
      {
        sourceId: "zf3_02_187",
        controller: "zf3",
        text: "Alitalia one three five zurich radar good afternoon identified trasadingen saronno maintain flight level three zero zero.",
        durationSeconds: 6.973,
        src: "examples/controllers/zf3/zf3_02_187.wav",
      },
      {
        sourceId: "zf3_02_152",
        controller: "zf3",
        text: "Alitalia two nine one zurich radar good afternoon trasadingen saronno maintain flight level three three zero.",
        durationSeconds: 6.1151875,
        src: "examples/controllers/zf3/zf3_02_152.wav",
      },
      {
        sourceId: "zf3_03_092",
        controller: "zf3",
        text: "Alitalia four zero four good morning squawk seven five three two.",
        durationSeconds: 3.2955625,
        src: "examples/controllers/zf3/zf3_03_092.wav",
      },
      {
        sourceId: "zf3_02_064",
        controller: "zf3",
        text: "Bama one five call milan one three four decimal five two bye bye.",
        durationSeconds: 4.1133125,
        src: "examples/controllers/zf3/zf3_02_064.wav",
      },
      {
        sourceId: "zf3_02_171",
        controller: "zf3",
        text: "Aerovic one zero six one own navigation to st prex.",
        durationSeconds: 3.028,
        src: "examples/controllers/zf3/zf3_02_171.wav",
      },
    ],
  },
};
